x=input("enter the first number: ")
y=input("enter the second number: ")
addition=int(x)+int(y)
subtraction= int(x) - int(y)
multiplication=int(x)*int(y)
division=int(x)/int(y)
print("addition:",addition)
print("subtraction:",subtraction)
print("multiplication:",multiplication)
print("division:",division)